{% set version = "0.2" %}

package:
  name: commanderline
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/commanderline/commanderline-{{ version }}.tar.gz
  sha256: 4f174ce90c5adb10cf7d9c2ed03e8b9c199dd90214466344be47ad1cbfff47a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - commanderline
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomazberisa/commanderline
  summary: Easily expose any function to the command line
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - danielnachun
